"""add reflection validations

Revision ID: 28df3bb0422e
Revises: a30c62ebbc5d
Create Date: 2026-07-08 11:15:27.603223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28df3bb0422e'
down_revision: Union[str, Sequence[str], None] = 'a30c62ebbc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflection_validation',
    sa.Column('reflection_id', sa.String(length=128), nullable=False),
    sa.Column('query_id', sa.String(length=128), nullable=False),
    sa.Column('profile_id', sa.String(length=128), nullable=False),
    sa.Column('interpretation_hash', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issues_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revision_instruction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['audit.result_profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['audit.query_run.query_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reflection_id'),
    sa.UniqueConstraint('query_id', 'interpretation_hash', name='uq_reflection_query_interpretation'),
    schema='audit'
    )
    op.create_index('ix_reflection_query_status', 'reflection_validation', ['query_id', 'status'], unique=False, schema='audit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reflection_query_status', table_name='reflection_validation', schema='audit')
    op.drop_table('reflection_validation', schema='audit')
    # ### end Alembic commands ###

