"""create control plane

Revision ID: 5bec1957b97f
Revises: 
Create Date: 2026-07-07 19:37:18.087268
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5bec1957b97f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS metric_center")
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_context',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('conversation_id', sa.String(length=128), nullable=False),
    sa.Column('operator_id', sa.String(length=128), nullable=False),
    sa.Column('last_query_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'conversation_id', name='uq_conversation_context'),
    schema='app'
    )
    op.create_table('query_run',
    sa.Column('query_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('workspace_id', sa.String(length=128), nullable=False),
    sa.Column('operator_id', sa.String(length=128), nullable=False),
    sa.Column('dsl_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dsl_hash', sa.String(length=80), nullable=False),
    sa.Column('sql_text', sa.Text(), nullable=False),
    sa.Column('sql_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sql_fingerprint', sa.String(length=80), nullable=False),
    sa.Column('metric_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lineage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('query_id'),
    schema='audit'
    )
    op.create_index('ix_query_run_status_created', 'query_run', ['status', 'created_at'], unique=False, schema='audit')
    op.create_index('ix_query_run_workspace_operator', 'query_run', ['workspace_id', 'operator_id'], unique=False, schema='audit')
    op.create_table('business_domain',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='metric_center'
    )
    op.create_table('dimension',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dimension_type', sa.String(length=32), nullable=False),
    sa.Column('mapping_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_operators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='metric_center'
    )
    op.create_table('metric',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_domain_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_domain_id'], ['metric_center.business_domain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='metric_center'
    )
    op.create_index('ix_metric_domain_status', 'metric', ['business_domain_id', 'status'], unique=False, schema='metric_center')
    op.create_table('semantic_model',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_domain_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('warehouse', sa.String(length=64), nullable=False),
    sa.Column('physical_table', sa.String(length=255), nullable=False),
    sa.Column('default_time_field', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['business_domain_id'], ['metric_center.business_domain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='metric_center'
    )
    op.create_index(op.f('ix_metric_center_semantic_model_business_domain_id'), 'semantic_model', ['business_domain_id'], unique=False, schema='metric_center')
    op.create_table('metric_alias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_center.metric.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_id', 'alias', name='uq_metric_alias'),
    schema='metric_center'
    )
    op.create_index('ix_metric_alias_alias', 'metric_alias', ['alias'], unique=False, schema='metric_center')
    op.create_table('metric_dimension',
    sa.Column('metric_id', sa.String(length=100), nullable=False),
    sa.Column('dimension_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['metric_center.dimension.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_center.metric.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id', 'dimension_id'),
    schema='metric_center'
    )
    op.create_table('metric_version',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('semantic_model_id', sa.String(length=100), nullable=False),
    sa.Column('expression_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_aggregation', sa.String(length=32), nullable=False),
    sa.Column('time_dimension_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_center.metric.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['metric_center.semantic_model.id'], ),
    sa.ForeignKeyConstraint(['time_dimension_id'], ['metric_center.dimension.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_id', 'version', name='uq_metric_version'),
    schema='metric_center'
    )
    op.create_index(op.f('ix_metric_center_metric_version_metric_id'), 'metric_version', ['metric_id'], unique=False, schema='metric_center')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_center_metric_version_metric_id'), table_name='metric_version', schema='metric_center')
    op.drop_table('metric_version', schema='metric_center')
    op.drop_table('metric_dimension', schema='metric_center')
    op.drop_index('ix_metric_alias_alias', table_name='metric_alias', schema='metric_center')
    op.drop_table('metric_alias', schema='metric_center')
    op.drop_index(op.f('ix_metric_center_semantic_model_business_domain_id'), table_name='semantic_model', schema='metric_center')
    op.drop_table('semantic_model', schema='metric_center')
    op.drop_index('ix_metric_domain_status', table_name='metric', schema='metric_center')
    op.drop_table('metric', schema='metric_center')
    op.drop_table('dimension', schema='metric_center')
    op.drop_table('business_domain', schema='metric_center')
    op.drop_index('ix_query_run_workspace_operator', table_name='query_run', schema='audit')
    op.drop_index('ix_query_run_status_created', table_name='query_run', schema='audit')
    op.drop_table('query_run', schema='audit')
    op.drop_table('conversation_context', schema='app')
    # ### end Alembic commands ###
